kind: pipeline
name: default

trigger:
  branch:
    - main
  event:
    - push

steps:
- name: test
  image: python
  environment:
    test_secret:
      from_secret: test_secret
  commands:
#   - pip install -r requirements.txt
#   - python test.py
  - echo $TEST_SECRET
